# ID3 tag mapping for human-readable names
ID3_TAG_NAMES = {
    'TIT2': 'Title',
    'TPE1': 'Artist',
    'TPE2': 'Album Artist',
    'TALB': 'Album',
    'TRCK': 'Track Number',
    'TDRC': 'Year',
    'TDRL': 'Release Date',
    'TDTG': 'Original Release Date',
    'TCOM': 'Composer',
    'TEXT': 'Lyricist',
    'TENC': 'Encoded By',
    'TSSE': 'Software/Hardware',
    'TXXX': 'Custom',
    'APIC:': 'Artwork',
    'COMM': 'Comment',
    'USLT': 'Lyrics',
    'TSRC': 'ISRC',
    'TCOP': 'Copyright',
    'TPUB': 'Publisher',
    'TENC': 'Encoded By',
    'TSSE': 'Settings',
    'TFLT': 'File Type',
    'TIME': 'Time',
    'TORY': 'Original Release Year',
    'TOAL': 'Original Album',
    'TOPE': 'Original Artist',
    'TOLY': 'Original Lyricist',
    'TOC': 'Original Composer',
    'TIT1': 'Content Group',
    'TIT3': 'Subtitle',
    'TIT4': 'Movement Name',
    'TKEY': 'Initial Key',
    'TMED': 'Media Type',
    'TMOO': 'Mood',
    'TPRO': 'Produced Notice',
    'TPUB': 'Publisher',
    'TRSN': 'Internet Radio Station Name',
    'TRSO': 'Internet Radio Station Owner',
    'TSIZ': 'Size',
    'TSRC': 'ISRC',
    'TSSE': 'Software/Hardware',
    'TXXX': 'User Defined Text',
    'WXXX': 'User Defined URL',
    'WCOM': 'Commercial Information URL',
    'WCOP': 'Copyright/Legal Information URL',
    'WOAF': 'Official Audio File Webpage',
    'WOAR': 'Official Artist/Performer Webpage',
    'WOAS': 'Official Audio Source Webpage',
    'WORS': 'Official Internet Radio Station Homepage',
    'WPAY': 'Payment URL',
    'WPUB': 'Publishers Official Webpage'
} 